/** FORTUNE NOIR Phase 1 backend
 * Cloudflare Worker + D1
 * Vars: ADMIN_PASSWORD, SESSION_SECRET
 * Binding: DB (D1)
 */
const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...extra}});
const cors=req=>{const origin=req.headers.get('Origin')||'';const allow=origin&&(origin.endsWith('.github.io')||origin==='http://localhost:3000'||origin==='http://127.0.0.1:5500');return allow?{'access-control-allow-origin':origin,'access-control-allow-credentials':'true','vary':'Origin'}:{}};
async function body(req){try{return await req.json()}catch{return {}}}
function bytesToHex(bytes){return [...new Uint8Array(bytes)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function sha256(text){return bytesToHex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))}
function token(){const b=new Uint8Array(32);crypto.getRandomValues(b);return bytesToHex(b)}
function normalizeName(v){return String(v||'').normalize('NFKC').trim().toLocaleLowerCase('en-US')}
function cleanName(v){return String(v||'').normalize('NFKC').trim()}
function validName(v){return /^[^\u0000-\u001F\u007F]{1,16}$/u.test(v) && v!=='391x'}
function decodePasswordB64(value){try{const bin=atob(String(value||''));const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)}catch{return null}}
async function session(req,env){const raw=req.headers.get('Authorization')||'';if(!raw.startsWith('Bearer '))return null;const t=raw.slice(7);if(!t)return null;const h=await sha256(t);const row=await env.DB.prepare('SELECT token_hash,player_id,role,expires_at FROM sessions WHERE token_hash=?').bind(h).first();if(!row||Number(row.expires_at)<Date.now())return null; if(row.role==='player'){const ctl=await env.DB.prepare('SELECT status FROM player_controls WHERE player_id=?').bind(row.player_id).first().catch(()=>null);if(ctl?.status==='frozen')return null; await env.DB.prepare('INSERT INTO player_presence(player_id,last_seen) VALUES(?,?) ON CONFLICT(player_id) DO UPDATE SET last_seen=excluded.last_seen').bind(row.player_id,Date.now()).run().catch(()=>{});}return row}
async function ensureSchema(env){
  await env.DB.batch([
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS players (player_id TEXT PRIMARY KEY, name TEXT NOT NULL, balance INTEGER NOT NULL DEFAULT 10000, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, player_id TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('player','admin')), expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS balance_ledger (id INTEGER PRIMARY KEY AUTOINCREMENT, tx_id TEXT NOT NULL UNIQUE, player_id TEXT NOT NULL, delta INTEGER NOT NULL, balance_after INTEGER NOT NULL, reason TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS admin_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, admin_player_id TEXT NOT NULL, target_player_id TEXT NOT NULL, amount INTEGER NOT NULL, note TEXT NOT NULL DEFAULT '', created_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS player_names (name_key TEXT PRIMARY KEY, player_id TEXT NOT NULL UNIQUE, name TEXT NOT NULL, created_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS player_controls (player_id TEXT PRIMARY KEY, status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','frozen')), note TEXT NOT NULL DEFAULT '', updated_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS friend_requests (id INTEGER PRIMARY KEY AUTOINCREMENT, requester_id TEXT NOT NULL, target_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','accepted','rejected')), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE UNIQUE INDEX IF NOT EXISTS idx_friend_requests_pending ON friend_requests(requester_id,target_id,status)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS friendships (player_id TEXT NOT NULL, friend_id TEXT NOT NULL, created_at INTEGER NOT NULL, PRIMARY KEY(player_id,friend_id))`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS rooms (room_id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, host_player_id TEXT NOT NULL, game_type TEXT NOT NULL CHECK(game_type IN ('poker','mahjong')), status TEXT NOT NULL DEFAULT 'waiting' CHECK(status IN ('waiting','playing','finished')), max_players INTEGER NOT NULL, created_at INTEGER NOT NULL, expires_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS room_members (room_id TEXT NOT NULL, player_id TEXT NOT NULL, ready INTEGER NOT NULL DEFAULT 0, joined_at INTEGER NOT NULL, PRIMARY KEY(room_id,player_id))`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS admin_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS player_presence (player_id TEXT PRIMARY KEY, last_seen INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS player_settings (player_id TEXT PRIMARY KEY, icon TEXT NOT NULL DEFAULT '♠', frame TEXT NOT NULL DEFAULT 'classic', language TEXT NOT NULL DEFAULT 'ja', sound INTEGER NOT NULL DEFAULT 1, notifications INTEGER NOT NULL DEFAULT 1, online_status INTEGER NOT NULL DEFAULT 1, reduced_motion INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS player_items (player_id TEXT NOT NULL, item_id TEXT NOT NULL, granted_by TEXT NOT NULL DEFAULT '', granted_at INTEGER NOT NULL, PRIMARY KEY(player_id,item_id))`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS room_invites (id INTEGER PRIMARY KEY AUTOINCREMENT, room_id TEXT NOT NULL, inviter_id TEXT NOT NULL, target_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','accepted','rejected')), created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE UNIQUE INDEX IF NOT EXISTS idx_room_invites_pending ON room_invites(room_id,target_id,status)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS game_settings (game_type TEXT PRIMARY KEY, enabled INTEGER NOT NULL DEFAULT 1, maintenance INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS reward_claims (player_id TEXT PRIMARY KEY, last_claim_at INTEGER NOT NULL DEFAULT 0, updated_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS poker_games (game_id TEXT PRIMARY KEY, room_id TEXT NOT NULL UNIQUE, status TEXT NOT NULL CHECK(status IN ('waiting','playing','finished')), dealer_index INTEGER NOT NULL DEFAULT 0, turn_index INTEGER NOT NULL DEFAULT 0, pot INTEGER NOT NULL DEFAULT 0, current_bet INTEGER NOT NULL DEFAULT 0, street TEXT NOT NULL DEFAULT 'preflop', board_json TEXT NOT NULL DEFAULT '[]', deck_json TEXT NOT NULL DEFAULT '[]', players_json TEXT NOT NULL DEFAULT '[]', created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS poker_actions (id INTEGER PRIMARY KEY AUTOINCREMENT, game_id TEXT NOT NULL, player_id TEXT NOT NULL, action TEXT NOT NULL, amount INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL)`),
  ]);
  const defaults=[['slot',1,0],['blackjack',1,0],['poker',1,0],['roulette',1,0],['crash',1,0],['highlow',1,0],['chohan',1,0],['cointoss',1,0],['highdice',1,0],['mahjong',1,0]];
  for(const [g,e,m] of defaults) await env.DB.prepare(`INSERT OR IGNORE INTO game_settings(game_type,enabled,maintenance,updated_at) VALUES(?,?,?,?)`).bind(g,e,m,Date.now()).run();
  const now=Date.now();
  await env.DB.prepare(`INSERT OR IGNORE INTO players(player_id,name,balance,created_at,updated_at) VALUES('391x','391x',10000,?,?)`).bind(now,now).run();
  await env.DB.prepare(`INSERT OR IGNORE INTO player_names(name_key,player_id,name,created_at) VALUES('391x','391x','391x',?)`).bind(now).run();
  await env.DB.prepare(`INSERT OR IGNORE INTO player_controls(player_id,status,note,updated_at) VALUES('391x','active','RESERVED ADMIN ACCOUNT',?)`).bind(now).run();
  await env.DB.prepare(`INSERT OR IGNORE INTO player_settings(player_id,icon,frame,language,sound,notifications,online_status,reduced_motion,updated_at) VALUES('391x','♠','gold','ja',1,1,1,0,?)`).bind(now).run();
}
async function playerByName(env,nameKey){return env.DB.prepare('SELECT player_id,name,balance,created_at,updated_at FROM players WHERE lower(name)=? LIMIT 1').bind(nameKey).first()}
async function requireSocialSession(req,env){const s=await session(req,env);if(!s||!((s.role==='player')||(s.role==='admin'&&s.player_id==='391x')))throw Object.assign(new Error('UNAUTHORIZED'),{status:401});return s}
async function requirePlayerSession(req,env){const s=await session(req,env);if(!s||s.role!=='player')throw Object.assign(new Error('UNAUTHORIZED'),{status:401});return s}
async function requireAdmin(req,env){const s=await session(req,env);if(!s||s.role!=='admin'||s.player_id!=='391x')throw Object.assign(new Error('FORBIDDEN'),{status:403});return s}
async function getRoomForPlayer(env,pid){return env.DB.prepare(`SELECT r.room_id,r.code,r.host_player_id,r.game_type,r.status,r.max_players,r.created_at,r.expires_at,rm.ready FROM room_members rm JOIN rooms r ON r.room_id=rm.room_id WHERE rm.player_id=? AND r.expires_at>? ORDER BY r.created_at DESC LIMIT 1`).bind(pid,Date.now()).first()}
async function roomState(env,roomId){
  const r=await env.DB.prepare('SELECT room_id,code,host_player_id,game_type,status,max_players,created_at,expires_at FROM rooms WHERE room_id=?').bind(roomId).first();if(!r)return null;
  const m=await env.DB.prepare('SELECT rm.player_id,rm.ready,p.name FROM room_members rm JOIN players p ON p.player_id=rm.player_id WHERE rm.room_id=? ORDER BY rm.joined_at').bind(roomId).all();
  return {...r,members:m.results||[]};
}
async function uniqueRoomCode(env){for(let i=0;i<30;i++){const code=String(Math.floor(1000+Math.random()*9000));const r=await env.DB.prepare('SELECT room_id FROM rooms WHERE code=? AND expires_at>?').bind(code,Date.now()).first();if(!r)return code}throw new Error('ROOM_CODE_UNAVAILABLE')}

export default {async fetch(req,env){
  const headers=cors(req);const url=new URL(req.url);const path=url.pathname.replace(/\/+$/,'')||'/';
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{...headers,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'Content-Type,Authorization'}});
  try{
    await ensureSchema(env);
    await env.DB.prepare('DELETE FROM rooms WHERE expires_at<?').bind(Date.now()).run();
    if(path==='/health')return json({ok:true,service:'FORTUNE_NOIR_ADMIN_API',version:'1.25.0'},200,headers);

    if(path==='/auth/login'&&req.method==='POST'){
      const b=await body(req);const username=String(b.username||'');const supplied=b.password_b64?decodePasswordB64(b.password_b64):String(b.password||'');
      if(username!=='391x'||!env.ADMIN_PASSWORD||supplied!==String(env.ADMIN_PASSWORD))return json({ok:false,error:'INVALID_CREDENTIALS'},401,headers);
      const t=token(),h=await sha256(t),exp=Date.now()+86400000;await env.DB.prepare('DELETE FROM sessions WHERE player_id=? AND role=?').bind('391x','admin').run();
      await env.DB.prepare('INSERT INTO sessions(token_hash,player_id,role,expires_at,created_at) VALUES(?,?,?,?,?)').bind(h,'391x','admin',exp,Date.now()).run();
      return json({ok:true,token:t,role:'admin',playerId:'391x',expiresAt:exp},200,headers);
    }
    if(path==='/auth/logout'&&req.method==='POST'){const raw=(req.headers.get('Authorization')||'').slice(7);if(raw)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(raw)).run();return json({ok:true},200,headers)}
    if(path==='/auth/me'&&req.method==='GET'){const s=await session(req,env);if(!s)return json({ok:false,authenticated:false},401,headers);return json({ok:true,authenticated:true,role:s.role,playerId:s.player_id},200,headers)}

    if(path==='/player/session'&&req.method==='POST'){
      const b=await body(req);const name=cleanName(b.name);const key=normalizeName(name);if(!name||!validName(name))return json({ok:false,error:'INVALID_PLAYER_NAME'},400,headers);if(key==='391x')return json({ok:false,error:'RESERVED_PLAYER_NAME'},409,headers);
      const existing=await env.DB.prepare('SELECT player_id,name,balance,created_at,updated_at FROM players WHERE lower(name)=? LIMIT 1').bind(key).first();
      const reserved=await env.DB.prepare('SELECT player_id FROM player_names WHERE name_key=?').bind(key).first();
      if(reserved && existing && reserved.player_id!==existing.player_id)return json({ok:false,error:'PLAYER_NAME_ALREADY_USED'},409,headers);
      let playerId=reserved?.player_id||existing?.player_id||'';
      if(playerId && !reserved){
        try{await env.DB.prepare('INSERT INTO player_names(name_key,player_id,name,created_at) VALUES(?,?,?,?)').bind(key,playerId,existing?.name||name,Date.now()).run()}catch(e){const owner=await env.DB.prepare('SELECT player_id FROM player_names WHERE name_key=?').bind(key).first();if(owner?.player_id!==playerId)return json({ok:false,error:'PLAYER_NAME_ALREADY_USED'},409,headers)}
      }
      if(!playerId){playerId=crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;const now=Date.now();
        try{await env.DB.batch([
          env.DB.prepare('INSERT INTO players(player_id,name,balance,created_at,updated_at) VALUES(?,?,?,?,?)').bind(playerId,name,10000,now,now),
          env.DB.prepare('INSERT INTO player_names(name_key,player_id,name,created_at) VALUES(?,?,?,?)').bind(key,playerId,name,now),
          env.DB.prepare('INSERT INTO player_controls(player_id,status,note,updated_at) VALUES(?,?,?,?)').bind(playerId,'active','',now),
          env.DB.prepare('INSERT INTO balance_ledger(tx_id,player_id,delta,balance_after,reason,created_at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),playerId,10000,10000,'INITIAL_REGISTRATION_BONUS',now),
          env.DB.prepare('INSERT INTO reward_claims(player_id,last_claim_at,updated_at) VALUES(?,?,?)').bind(playerId,0,now)
        ])}catch(e){const again=await env.DB.prepare('SELECT player_id,name,balance FROM players WHERE lower(name)=? LIMIT 1').bind(key).first();if(again)playerId=again.player_id;else throw e}
      }
      const ctl=await env.DB.prepare('SELECT status FROM player_controls WHERE player_id=?').bind(playerId).first().catch(()=>null);if(ctl?.status==='frozen')return json({ok:false,error:'PLAYER_FROZEN'},403,headers);
      const p=await env.DB.prepare('SELECT player_id,name,balance,created_at,updated_at FROM players WHERE player_id=?').bind(playerId).first();
      await env.DB.prepare(`INSERT OR IGNORE INTO player_settings(player_id,icon,frame,language,sound,notifications,online_status,reduced_motion,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(playerId,'♠','classic','ja',1,1,1,0,Date.now()).run();
      const t=token(),h=await sha256(t),exp=Date.now()+30*86400000;await env.DB.prepare('INSERT INTO sessions(token_hash,player_id,role,expires_at,created_at) VALUES(?,?,?,?,?)').bind(h,playerId,'player',exp,Date.now()).run();
      await env.DB.prepare('UPDATE players SET updated_at=? WHERE player_id=?').bind(Date.now(),playerId).run();
      return json({ok:true,token:t,playerId,balance:Number(p.balance),name:p.name,expiresAt:exp},200,headers);
    }
    if(path==='/balance'&&req.method==='GET'){const s=await requireSocialSession(req,env);const p=await env.DB.prepare('SELECT player_id,balance,name FROM players WHERE player_id=?').bind(s.player_id).first();if(!p)return json({ok:false,error:'PLAYER_NOT_FOUND'},404,headers);return json({ok:true,playerId:p.player_id,balance:Number(p.balance),name:p.name},200,headers)}
    if(path==='/player/adjust'&&req.method==='POST'){
      const s=await requirePlayerSession(req,env);const b=await body(req),delta=Number(b.delta),txId=String(b.txId||'').slice(0,100);if(!Number.isSafeInteger(delta)||delta===0||Math.abs(delta)>1000000000||!txId)return json({ok:false,error:'INVALID_ADJUST'},400,headers);
      const old=await env.DB.prepare('SELECT balance FROM players WHERE player_id=?').bind(s.player_id).first();if(!old)return json({ok:false,error:'PLAYER_NOT_FOUND'},404,headers);const dup=await env.DB.prepare('SELECT id,balance_after FROM balance_ledger WHERE tx_id=?').bind(txId).first();if(dup)return json({ok:true,balance:Number(dup.balance_after),duplicate:true},200,headers);const next=Number(old.balance)+delta;if(next<0)return json({ok:false,error:'INSUFFICIENT_BALANCE'},400,headers);
      await env.DB.batch([env.DB.prepare('UPDATE players SET balance=?,updated_at=? WHERE player_id=?').bind(next,Date.now(),s.player_id),env.DB.prepare('INSERT INTO balance_ledger(tx_id,player_id,delta,balance_after,reason,created_at) VALUES(?,?,?,?,?,?)').bind(txId,s.player_id,delta,next,String(b.reason||'GAME').slice(0,80),Date.now())]);return json({ok:true,balance:next,delta},200,headers);
    }

    if(path==='/rewards/5h'&&req.method==='GET'){const s=await requirePlayerSession(req,env);const row=await env.DB.prepare('SELECT last_claim_at FROM reward_claims WHERE player_id=?').bind(s.player_id).first();const last=Number(row?.last_claim_at||0);const next=last+18000000;return json({ok:true,amount:5000,claimable:Date.now()>=next,lastClaimAt:last,nextClaimAt:next},200,headers)}
    if(path==='/rewards/5h'&&req.method==='POST'){const s=await requirePlayerSession(req,env);const now=Date.now();const row=await env.DB.prepare('SELECT last_claim_at FROM reward_claims WHERE player_id=?').bind(s.player_id).first();const last=Number(row?.last_claim_at||0);if(last&&now-last<18000000)return json({ok:false,error:'REWARD_COOLDOWN',amount:5000,lastClaimAt:last,nextClaimAt:last+18000000},409,headers);const p=await env.DB.prepare('SELECT balance FROM players WHERE player_id=?').bind(s.player_id).first();if(!p)return json({ok:false,error:'PLAYER_NOT_FOUND'},404,headers);const nextBalance=Number(p.balance)+5000;const txId=crypto.randomUUID();await env.DB.batch([env.DB.prepare('UPDATE players SET balance=?,updated_at=? WHERE player_id=?').bind(nextBalance,now,s.player_id),env.DB.prepare('INSERT INTO balance_ledger(tx_id,player_id,delta,balance_after,reason,created_at) VALUES(?,?,?,?,?,?)').bind(txId,s.player_id,5000,nextBalance,'5H_REWARD',now),env.DB.prepare(`INSERT INTO reward_claims(player_id,last_claim_at,updated_at) VALUES(?,?,?) ON CONFLICT(player_id) DO UPDATE SET last_claim_at=excluded.last_claim_at,updated_at=excluded.updated_at`).bind(s.player_id,now,now)]);return json({ok:true,amount:5000,balance:nextBalance,lastClaimAt:now,nextClaimAt:now+18000000},200,headers)}

    // Profile settings
    if(path==='/profile/settings'&&req.method==='GET'){const s=await requireSocialSession(req,env);await env.DB.prepare(`INSERT OR IGNORE INTO player_settings(player_id,icon,frame,language,sound,notifications,online_status,reduced_motion,updated_at) VALUES(?,?,?,?,?,?,?,?,?)`).bind(s.player_id,'♠',s.player_id==='391x'?'gold':'classic','ja',1,1,1,0,Date.now()).run();const x=await env.DB.prepare('SELECT icon,frame,language,sound,notifications,online_status,reduced_motion,updated_at FROM player_settings WHERE player_id=?').bind(s.player_id).first();const owned=await env.DB.prepare("SELECT item_id FROM player_items WHERE player_id=? ORDER BY item_id").bind(s.player_id).all().catch(()=>({results:[]}));const ownedFrames=['classic','gold','silver','neon','royal'];for(const it of (owned.results||[])){if(String(it.item_id).startsWith('frame:'))ownedFrames.push(String(it.item_id).slice(6));}return json({ok:true,settings:{icon:x.icon,frame:x.frame,language:x.language,sound:!!x.sound,notifications:!!x.notifications,onlineStatus:!!x.online_status,reducedMotion:!!x.reduced_motion,updatedAt:x.updated_at,ownedFrames:[...new Set(ownedFrames)]}},200,headers)}
    if(path==='/profile/settings'&&req.method==='POST'){const s=await requireSocialSession(req,env);const b=await body(req);const icon=String(b.icon||'♠').slice(0,4),frame=String(b.frame||'classic').slice(0,20),language=['ja','en'].includes(String(b.language))?String(b.language):'ja';const allowedBase=['classic','gold','silver','neon','royal'];if(!allowedBase.includes(frame)){const owned=await env.DB.prepare('SELECT 1 FROM player_items WHERE player_id=? AND item_id=?').bind(s.player_id,'frame:'+frame).first();if(!owned)return json({ok:false,error:'ITEM_NOT_OWNED'},403,headers)}const now=Date.now();await env.DB.prepare(`INSERT INTO player_settings(player_id,icon,frame,language,sound,notifications,online_status,reduced_motion,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(player_id) DO UPDATE SET icon=excluded.icon,frame=excluded.frame,language=excluded.language,sound=excluded.sound,notifications=excluded.notifications,online_status=excluded.online_status,reduced_motion=excluded.reduced_motion,updated_at=excluded.updated_at`).bind(s.player_id,icon,frame,language,b.sound===false?0:1,b.notifications===false?0:1,b.onlineStatus===false?0:1,b.reducedMotion?1:0,now).run();return json({ok:true,settings:{icon,frame,language,sound:b.sound!==false,notifications:b.notifications!==false,onlineStatus:b.onlineStatus!==false,reducedMotion:!!b.reducedMotion,updatedAt:now}},200,headers)}

    // Friends
    if(path==='/players/search'&&req.method==='GET'){const s=await requireSocialSession(req,env);const u=new URL(req.url);const q=cleanName(u.searchParams.get('q')||'');if(q.length<1)return json({ok:true,players:[]},200,headers);const key=normalizeName(q);const rows=await env.DB.prepare(`SELECT player_id,name,created_at,updated_at FROM players WHERE lower(name) LIKE ? AND player_id<>? ORDER BY name LIMIT 20`).bind('%'+key+'%',s.player_id).all();return json({ok:true,players:rows.results||[]},200,headers)}
    if(path==='/friends/list'&&req.method==='GET'){const s=await requireSocialSession(req,env);const rows=await env.DB.prepare(`SELECT f.friend_id AS player_id,p.name,p.updated_at,CASE WHEN COALESCE(pp.last_seen,0)>=? THEN 1 ELSE 0 END AS online FROM friendships f JOIN players p ON p.player_id=f.friend_id LEFT JOIN player_presence pp ON pp.player_id=f.friend_id WHERE f.player_id=? ORDER BY online DESC,p.name`).bind(Date.now()-120000,s.player_id).all();return json({ok:true,friends:rows.results||[]},200,headers)}
    if(path==='/friends/remove'&&req.method==='POST'){const s=await requireSocialSession(req,env);const b=await body(req),friendId=String(b.friendId||'').trim();if(!friendId||friendId===s.player_id)return json({ok:false,error:'INVALID_FRIEND_ID'},400,headers);await env.DB.batch([env.DB.prepare('DELETE FROM friendships WHERE player_id=? AND friend_id=?').bind(s.player_id,friendId),env.DB.prepare('DELETE FROM friendships WHERE player_id=? AND friend_id=?').bind(friendId,s.player_id)]);return json({ok:true},200,headers)}
    if(path==='/friends/requests'&&req.method==='GET'){const s=await requireSocialSession(req,env);const incoming=await env.DB.prepare(`SELECT fr.id,fr.requester_id AS player_id,p.name,fr.created_at FROM friend_requests fr JOIN players p ON p.player_id=fr.requester_id WHERE fr.target_id=? AND fr.status='pending' ORDER BY fr.id DESC`).bind(s.player_id).all();const outgoing=await env.DB.prepare(`SELECT fr.id,fr.target_id AS player_id,p.name,fr.created_at FROM friend_requests fr JOIN players p ON p.player_id=fr.target_id WHERE fr.requester_id=? AND fr.status='pending' ORDER BY fr.id DESC`).bind(s.player_id).all();return json({ok:true,incoming:incoming.results||[],outgoing:outgoing.results||[]},200,headers)}
    if(path==='/friends/request'&&req.method==='POST'){const s=await requireSocialSession(req,env);const b=await body(req);const targetName=cleanName(b.targetName);const targetKey=normalizeName(targetName);const target=await env.DB.prepare('SELECT player_id,name FROM players WHERE lower(name)=? LIMIT 1').bind(targetKey).first();if(!target)return json({ok:false,error:'PLAYER_NOT_FOUND'},404,headers);if(target.player_id===s.player_id)return json({ok:false,error:'CANNOT_FRIEND_SELF'},400,headers);const ex=await env.DB.prepare(`SELECT id,status FROM friend_requests WHERE requester_id=? AND target_id=? AND status='pending'`).bind(s.player_id,target.player_id).first();if(ex)return json({ok:false,error:'REQUEST_EXISTS'},409,headers);const rev=await env.DB.prepare(`SELECT id,status FROM friend_requests WHERE requester_id=? AND target_id=? AND status='pending'`).bind(target.player_id,s.player_id).first();if(rev)return json({ok:false,error:'INCOMING_REQUEST_EXISTS'},409,headers);const now=Date.now();const r=await env.DB.prepare('INSERT INTO friend_requests(requester_id,target_id,status,created_at,updated_at) VALUES(?,?,?,?,?) RETURNING id').bind(s.player_id,target.player_id,'pending',now,now).first();return json({ok:true,requestId:Number(r.id),target:target.name},200,headers)}
    if(path==='/friends/respond'&&req.method==='POST'){const s=await requireSocialSession(req,env);const b=await body(req),id=Number(b.requestId),action=String(b.action||'');if(!Number.isSafeInteger(id)||!['accept','reject'].includes(action))return json({ok:false,error:'INVALID_REQUEST'},400,headers);const r=await env.DB.prepare('SELECT id,requester_id,target_id,status FROM friend_requests WHERE id=? AND target_id=? AND status=\'pending\'').bind(id,s.player_id).first();if(!r)return json({ok:false,error:'REQUEST_NOT_FOUND'},404,headers);if(action==='reject'){await env.DB.prepare('UPDATE friend_requests SET status=\'rejected\',updated_at=? WHERE id=?').bind(Date.now(),id);return json({ok:true,status:'rejected'},200,headers)}await env.DB.batch([env.DB.prepare('UPDATE friend_requests SET status=\'accepted\',updated_at=? WHERE id=?').bind(Date.now(),id),env.DB.prepare('INSERT OR IGNORE INTO friendships(player_id,friend_id,created_at) VALUES(?,?,?)').bind(r.requester_id,r.target_id,Date.now()),env.DB.prepare('INSERT OR IGNORE INTO friendships(player_id,friend_id,created_at) VALUES(?,?,?)').bind(r.target_id,r.requester_id,Date.now())]);return json({ok:true,status:'accepted'},200,headers)}

    // Room invites
    if(path==='/rooms/invite'&&req.method==='POST'){const s=await requireSocialSession(req,env);const b=await body(req),targetId=String(b.targetId||'').trim();const r=await getRoomForPlayer(env,s.player_id);if(!r||r.host_player_id!==s.player_id)return json({ok:false,error:'HOST_ONLY'},403,headers);if(!targetId)return json({ok:false,error:'INVALID_TARGET'},400,headers);const f=await env.DB.prepare('SELECT 1 FROM friendships WHERE player_id=? AND friend_id=?').bind(s.player_id,targetId).first();if(!f)return json({ok:false,error:'NOT_FRIEND'},403,headers);const now=Date.now();await env.DB.prepare('INSERT INTO room_invites(room_id,inviter_id,target_id,status,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(r.room_id,s.player_id,targetId,'pending',now,now).run();return json({ok:true},200,headers)}
    if(path==='/rooms/invites'&&req.method==='GET'){const s=await requireSocialSession(req,env);const rows=await env.DB.prepare(`SELECT ri.id,ri.room_id,ri.inviter_id,p.name,ri.created_at,r.code,r.game_type FROM room_invites ri JOIN players p ON p.player_id=ri.inviter_id JOIN rooms r ON r.room_id=ri.room_id WHERE ri.target_id=? AND ri.status='pending' AND r.expires_at>? ORDER BY ri.id DESC`).bind(s.player_id,Date.now()).all();return json({ok:true,invites:rows.results||[]},200,headers)}
    if(path==='/rooms/invite/respond'&&req.method==='POST'){const s=await requireSocialSession(req,env);const b=await body(req),id=Number(b.inviteId),action=String(b.action||'');if(!Number.isSafeInteger(id)||!['accept','reject'].includes(action))return json({ok:false,error:'INVALID_INVITE'},400,headers);const inv=await env.DB.prepare(`SELECT ri.*,r.max_players,r.expires_at FROM room_invites ri JOIN rooms r ON r.room_id=ri.room_id WHERE ri.id=? AND ri.target_id=? AND ri.status='pending'`).bind(id,s.player_id).first();if(!inv)return json({ok:false,error:'INVITE_NOT_FOUND'},404,headers);if(action==='reject'){await env.DB.prepare("UPDATE room_invites SET status='rejected',updated_at=? WHERE id=?").bind(Date.now(),id).run();return json({ok:true,status:'rejected'},200,headers)}const current=await getRoomForPlayer(env,s.player_id);if(current)return json({ok:false,error:'ALREADY_IN_ROOM'},409,headers);const count=await env.DB.prepare('SELECT COUNT(*) AS count FROM room_members WHERE room_id=?').bind(inv.room_id).first();if(Number(count.count)>=Number(inv.max_players))return json({ok:false,error:'ROOM_FULL'},409,headers);await env.DB.batch([env.DB.prepare('INSERT INTO room_members(room_id,player_id,ready,joined_at) VALUES(?,?,0,?)').bind(inv.room_id,s.player_id,Date.now()),env.DB.prepare("UPDATE room_invites SET status='accepted',updated_at=? WHERE id=?").bind(Date.now(),id)]);return json({ok:true,status:'accepted',room:await roomState(env,inv.room_id)},200,headers)}

    // Rooms: Phase 1 connection base, Poker now; Mahjong reserved for future.
    if(path==='/rooms/create'&&req.method==='POST'){const s=await requireSocialSession(req,env);const b=await body(req),gameType=String(b.gameType||'poker').toLowerCase();if(!['poker','mahjong'].includes(gameType))return json({ok:false,error:'INVALID_GAME_TYPE'},400,headers);const current=await getRoomForPlayer(env,s.player_id);if(current)return json({ok:false,error:'ALREADY_IN_ROOM',room:await roomState(env,current.room_id)},409,headers);const code=await uniqueRoomCode(env),roomId=crypto.randomUUID(),now=Date.now(),ttl=60*60*1000,maxPlayers=gameType==='mahjong'?3:6;await env.DB.batch([env.DB.prepare('INSERT INTO rooms(room_id,code,host_player_id,game_type,status,max_players,created_at,expires_at) VALUES(?,?,?,?,?,?,?,?)').bind(roomId,code,s.player_id,gameType,'waiting',maxPlayers,now,now+ttl),env.DB.prepare('INSERT INTO room_members(room_id,player_id,ready,joined_at) VALUES(?,?,0,?)').bind(roomId,s.player_id,now)]);return json({ok:true,room:await roomState(env,roomId)},200,headers)}
    if(path==='/rooms/join'&&req.method==='POST'){const s=await requireSocialSession(req,env);const b=await body(req),code=String(b.code||'').replace(/\\D/g,'').slice(0,4);if(!/^\\d{4}$/.test(code))return json({ok:false,error:'INVALID_ROOM_CODE'},400,headers);const current=await getRoomForPlayer(env,s.player_id);if(current)return json({ok:false,error:'ALREADY_IN_ROOM',room:await roomState(env,current.room_id)},409,headers);const r=await env.DB.prepare('SELECT room_id,code,host_player_id,game_type,status,max_players,created_at,expires_at FROM rooms WHERE code=? AND expires_at>?').bind(code,Date.now()).first();if(!r)return json({ok:false,error:'ROOM_NOT_FOUND'},404,headers);const count=await env.DB.prepare('SELECT COUNT(*) AS count FROM room_members WHERE room_id=?').bind(r.room_id).first();if(Number(count.count)>=Number(r.max_players))return json({ok:false,error:'ROOM_FULL'},409,headers);await env.DB.prepare('INSERT INTO room_members(room_id,player_id,ready,joined_at) VALUES(?,?,0,?)').bind(r.room_id,s.player_id,Date.now()).run();return json({ok:true,room:await roomState(env,r.room_id)},200,headers)}
    if(path==='/rooms/current'&&req.method==='GET'){const s=await requireSocialSession(req,env);const r=await getRoomForPlayer(env,s.player_id);return json({ok:true,room:r?await roomState(env,r.room_id):null},200,headers)}
    if(path==='/rooms/leave'&&req.method==='POST'){const s=await requireSocialSession(req,env);const r=await getRoomForPlayer(env,s.player_id);if(!r)return json({ok:true,room:null},200,headers);if(r.host_player_id===s.player_id){await env.DB.prepare('DELETE FROM room_members WHERE room_id=?').bind(r.room_id).run();await env.DB.prepare('DELETE FROM rooms WHERE room_id=?').bind(r.room_id).run()}else{await env.DB.prepare('DELETE FROM room_members WHERE room_id=? AND player_id=?').bind(r.room_id,s.player_id).run()}return json({ok:true},200,headers)}
    if(path==='/rooms/ready'&&req.method==='POST'){const s=await requireSocialSession(req,env);const b=await body(req);const ready=!!b.ready;const r=await getRoomForPlayer(env,s.player_id);if(!r)return json({ok:false,error:'NOT_IN_ROOM'},404,headers);await env.DB.prepare('UPDATE room_members SET ready=? WHERE room_id=? AND player_id=?').bind(ready?1:0,r.room_id,s.player_id).run();return json({ok:true,room:await roomState(env,r.room_id)},200,headers)}
    if(path==='/rooms/start'&&req.method==='POST'){const s=await requireSocialSession(req,env);const r=await getRoomForPlayer(env,s.player_id);if(!r||r.host_player_id!==s.player_id)return json({ok:false,error:'HOST_ONLY'},403,headers);const count=await env.DB.prepare('SELECT COUNT(*) AS count FROM room_members WHERE room_id=?').bind(r.room_id).first();const unready=await env.DB.prepare('SELECT COUNT(*) AS count FROM room_members WHERE room_id=? AND ready=0').bind(r.room_id).first();const minPlayers=r.game_type==='poker'?2:3;if(Number(count.count)<minPlayers)return json({ok:false,error:'NOT_ENOUGH_PLAYERS'},409,headers);if(Number(unready.count)>0)return json({ok:false,error:'NOT_ALL_READY'},409,headers);await env.DB.prepare("UPDATE rooms SET status='playing' WHERE room_id=?").bind(r.room_id).run();return json({ok:true,room:await roomState(env,r.room_id)},200,headers)}

    // Phase 2: online poker server state foundation
    if(path==='/poker/state'&&req.method==='GET'){const s=await requireSocialSession(req,env);const r=await getRoomForPlayer(env,s.player_id);if(!r||r.game_type!=='poker')return json({ok:false,error:'NOT_IN_POKER_ROOM'},409,headers);let g=await env.DB.prepare('SELECT * FROM poker_games WHERE room_id=?').bind(r.room_id).first();if(!g){const members=(await env.DB.prepare('SELECT rm.player_id,p.name,p.balance FROM room_members rm JOIN players p ON p.player_id=rm.player_id WHERE rm.room_id=? ORDER BY rm.joined_at').bind(r.room_id).all()).results||[];const now=Date.now();const gameId=crypto.randomUUID();const deck=[];for(const suit of ['S','H','D','C'])for(const rank of ['2','3','4','5','6','7','8','9','T','J','Q','K','A'])deck.push(rank+suit);for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]];}const seats=members.map((m,i)=>({playerId:m.player_id,name:m.name,seat:i,stack:Number(m.balance||0),bet:0,folded:false,cards:[deck.pop(),deck.pop()]}));const board=[deck.pop(),deck.pop(),deck.pop(),deck.pop(),deck.pop()];g={game_id:gameId,room_id:r.room_id,status:r.status==='playing'?'playing':'waiting',dealer_index:0,turn_index:Math.min(1,seats.length-1),pot:0,current_bet:0,street:'preflop',board_json:JSON.stringify(board),deck_json:JSON.stringify(deck),players_json:JSON.stringify(seats),created_at:now,updated_at:now};await env.DB.prepare('INSERT INTO poker_games(game_id,room_id,status,dealer_index,turn_index,pot,current_bet,street,board_json,deck_json,players_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(gameId,r.room_id,g.status,g.dealer_index,g.turn_index,g.pot,g.current_bet,g.street,g.board_json,g.deck_json,g.players_json,g.created_at,g.updated_at).run();}
      const allPlayers=JSON.parse(g.players_json||'[]');const safePlayers=allPlayers.map(p=>({playerId:p.playerId,name:p.name,seat:p.seat,stack:p.stack,bet:p.bet,folded:p.folded,cards:p.playerId===s.player_id?p.cards:p.cards.map(()=>null)}));return json({ok:true,game:{gameId:g.game_id,roomId:g.room_id,status:g.status,street:g.street,dealerIndex:g.dealer_index,turnIndex:g.turn_index,pot:g.pot,currentBet:g.current_bet,board:JSON.parse(g.board_json||'[]').map((c,i)=>g.street==='showdown'?c:null),players:safePlayers,reconnect:true}},200,headers)}
    if(path==='/poker/action'&&req.method==='POST'){const s=await requireSocialSession(req,env);const r=await getRoomForPlayer(env,s.player_id);if(!r||r.game_type!=='poker')return json({ok:false,error:'NOT_IN_POKER_ROOM'},409,headers);const g=await env.DB.prepare('SELECT * FROM poker_games WHERE room_id=?').bind(r.room_id).first();if(!g)return json({ok:false,error:'POKER_GAME_NOT_INITIALIZED'},409,headers);if(g.status!=='playing')return json({ok:false,error:'POKER_NOT_STARTED'},409,headers);const payload=await body(req);const action=String(payload.action||'').toUpperCase();const players=JSON.parse(g.players_json||'[]');const idx=players.findIndex(p=>p.playerId===s.player_id);if(idx<0)return json({ok:false,error:'PLAYER_NOT_IN_GAME'},403,headers);if(idx!==Number(g.turn_index))return json({ok:false,error:'NOT_YOUR_TURN'},409,headers);const p=players[idx];if(['FOLD','CHECK','CALL','BET','RAISE'].indexOf(action)<0)return json({ok:false,error:'INVALID_POKER_ACTION'},400,headers);let amount=0;if(action==='CALL')amount=Math.max(0,Number(g.current_bet)-Number(p.bet));if(action==='BET'||action==='RAISE'){amount=Math.max(0,Number(payload.amount)||0);}if(amount>Number(p.stack))return json({ok:false,error:'INSUFFICIENT_STACK'},400,headers);if(action==='CHECK'&&Number(g.current_bet)!==Number(p.bet))return json({ok:false,error:'CANNOT_CHECK'},409,headers);if(action!=='FOLD'){p.stack-=amount;p.bet+=amount;g.pot=Number(g.pot)+amount;if(p.bet>Number(g.current_bet))g.current_bet=p.bet;}else p.folded=true;await env.DB.batch([env.DB.prepare('INSERT INTO poker_actions(game_id,player_id,action,amount,created_at) VALUES(?,?,?,?,?)').bind(g.game_id,s.player_id,action,amount,Date.now()),env.DB.prepare('UPDATE poker_games SET pot=?,current_bet=?,turn_index=?,players_json=?,updated_at=? WHERE game_id=?').bind(g.pot,g.current_bet,(idx+1)%players.length,JSON.stringify(players),Date.now(),g.game_id)]);return json({ok:true,action,amount,pot:g.pot,currentBet:g.current_bet,nextTurn:(idx+1)%players.length},200,headers)}

    // Admin
    if(path==='/admin/grant'&&req.method==='POST'){const s=await requireAdmin(req,env);const b=await body(req),target=String(b.playerId||b.playerName||'').trim(),amount=Number(b.amount);if(!target||!Number.isSafeInteger(amount)||amount===0||Math.abs(amount)>1000000000)return json({ok:false,error:'INVALID_GRANT'},400,headers);let playerId=target;let p=await env.DB.prepare('SELECT player_id,balance FROM players WHERE player_id=?').bind(playerId).first();if(!p){p=await env.DB.prepare('SELECT player_id,balance FROM players WHERE lower(name)=? LIMIT 1').bind(normalizeName(target)).first();if(p)playerId=p.player_id}if(!p)return json({ok:false,error:'PLAYER_NOT_FOUND'},404,headers);const next=Number(p.balance)+amount;if(next<0)return json({ok:false,error:'INSUFFICIENT_PLAYER_BALANCE'},400,headers);const now=Date.now(),txId=crypto.randomUUID(),note=String(b.note||'ADMIN').slice(0,200);try{await env.DB.prepare('UPDATE players SET balance=?,updated_at=? WHERE player_id=?').bind(next,now,playerId).run();await env.DB.prepare('INSERT INTO balance_ledger(tx_id,player_id,delta,balance_after,reason,created_at) VALUES(?,?,?,?,?,?)').bind(txId,playerId,amount,note.slice(0,80),now).run();try{await env.DB.prepare('INSERT INTO admin_logs(admin_player_id,target_player_id,amount,note,created_at) VALUES(?,?,?,?,?)').bind(s.player_id,playerId,amount,note,now).run()}catch(logErr){await env.DB.prepare("INSERT INTO admin_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind('last_admin_grant_warning',String(logErr?.message||logErr).slice(0,400),now).run().catch(()=>{})}return json({ok:true,playerId,balance:next,amount},200,headers)}catch(err){return json({ok:false,error:'GRANT_FAILED',detail:String(err?.message||err)},500,headers)}}
    if(path==='/admin/item/grant'&&req.method==='POST'){const s=await requireAdmin(req,env);const b=await body(req),target=String(b.playerId||b.playerName||'').trim(),itemId=String(b.itemId||'').trim();if(!target||!itemId||!/^[a-z0-9:_-]{2,64}$/i.test(itemId))return json({ok:false,error:'INVALID_ITEM'},400,headers);let p=await env.DB.prepare('SELECT player_id,name FROM players WHERE player_id=?').bind(target).first();if(!p)p=await env.DB.prepare('SELECT player_id,name FROM players WHERE lower(name)=? LIMIT 1').bind(normalizeName(target)).first();if(!p)return json({ok:false,error:'PLAYER_NOT_FOUND'},404,headers);const now=Date.now();await env.DB.prepare('INSERT OR IGNORE INTO player_items(player_id,item_id,granted_by,granted_at) VALUES(?,?,?,?)').bind(p.player_id,itemId,s.player_id,now).run();return json({ok:true,playerId:p.player_id,name:p.name,itemId,granted:true},200,headers)}
    if(path==='/admin/players'&&req.method==='GET'){await requireAdmin(req,env);const q=String(url.searchParams.get('q')||'').trim();const rows=q?await env.DB.prepare('SELECT p.player_id,p.name,p.balance,p.created_at,p.updated_at,COALESCE(pc.status,\'active\') AS status FROM players p LEFT JOIN player_controls pc ON pc.player_id=p.player_id WHERE p.player_id LIKE ? OR p.name LIKE ? ORDER BY p.updated_at DESC LIMIT 200').bind(`%${q}%`,`%${q}%`).all():await env.DB.prepare('SELECT p.player_id,p.name,p.balance,p.created_at,p.updated_at,COALESCE(pc.status,\'active\') AS status FROM players p LEFT JOIN player_controls pc ON pc.player_id=p.player_id ORDER BY p.updated_at DESC LIMIT 200').all();return json({ok:true,players:rows.results||[]},200,headers)}
    if(path==='/admin/player'&&req.method==='GET'){await requireAdmin(req,env);const playerId=String(url.searchParams.get('playerId')||'').trim();const p=await env.DB.prepare('SELECT p.player_id,p.name,p.balance,p.created_at,p.updated_at,COALESCE(pc.status,\'active\') AS status FROM players p LEFT JOIN player_controls pc ON pc.player_id=p.player_id WHERE p.player_id=?').bind(playerId).first();if(!p)return json({ok:false,error:'PLAYER_NOT_FOUND'},404,headers);const logs=await env.DB.prepare('SELECT id,delta,balance_after,reason,created_at FROM balance_ledger WHERE player_id=? ORDER BY id DESC LIMIT 50').bind(playerId).all();return json({ok:true,player:p,transactions:logs.results||[]},200,headers)}
    if(path==='/admin/player/delete'&&req.method==='POST'){const s=await requireAdmin(req,env);const b=await body(req),playerId=String(b.playerId||'').trim();if(!playerId||playerId==='391x')return json({ok:false,error:'CANNOT_DELETE_ADMIN'},403,headers);const p=await env.DB.prepare('SELECT player_id,name FROM players WHERE player_id=?').bind(playerId).first();if(!p)return json({ok:false,error:'PLAYER_NOT_FOUND'},404,headers);const rooms=await env.DB.prepare('SELECT room_id,host_player_id FROM rooms WHERE host_player_id=?').bind(playerId).all();const roomIds=(rooms.results||[]).map(x=>x.room_id);const stmts=[env.DB.prepare('DELETE FROM sessions WHERE player_id=?').bind(playerId),env.DB.prepare('DELETE FROM player_names WHERE player_id=?').bind(playerId),env.DB.prepare('DELETE FROM player_controls WHERE player_id=?').bind(playerId),env.DB.prepare('DELETE FROM player_presence WHERE player_id=?').bind(playerId),env.DB.prepare('DELETE FROM player_settings WHERE player_id=?').bind(playerId),env.DB.prepare('DELETE FROM friend_requests WHERE requester_id=? OR target_id=?').bind(playerId,playerId),env.DB.prepare('DELETE FROM friendships WHERE player_id=? OR friend_id=?').bind(playerId,playerId),env.DB.prepare('DELETE FROM room_invites WHERE inviter_id=? OR target_id=?').bind(playerId,playerId),env.DB.prepare('DELETE FROM room_members WHERE player_id=?').bind(playerId),env.DB.prepare('DELETE FROM balance_ledger WHERE player_id=?').bind(playerId),env.DB.prepare('DELETE FROM admin_logs WHERE target_player_id=?').bind(playerId),env.DB.prepare('DELETE FROM players WHERE player_id=?').bind(playerId)];for(const rid of roomIds)stmts.push(env.DB.prepare('DELETE FROM room_members WHERE room_id=?').bind(rid),env.DB.prepare('DELETE FROM room_invites WHERE room_id=?').bind(rid),env.DB.prepare('DELETE FROM rooms WHERE room_id=?').bind(rid));await env.DB.batch(stmts);return json({ok:true,playerId,name:p.name,deleted:true},200,headers)}
    if(path==='/admin/player/status'&&req.method==='POST'){const s=await requireAdmin(req,env);const b=await body(req),playerId=String(b.playerId||'').trim(),status=String(b.status||'');if(playerId==='391x')return json({ok:false,error:'CANNOT_MODIFY_ADMIN'},403,headers);if(!['active','frozen'].includes(status))return json({ok:false,error:'INVALID_STATUS'},400,headers);await env.DB.prepare(`INSERT INTO player_controls(player_id,status,note,updated_at) VALUES(?,?,?,?) ON CONFLICT(player_id) DO UPDATE SET status=excluded.status,note=excluded.note,updated_at=excluded.updated_at`).bind(playerId,status,String(b.note||'').slice(0,200),Date.now()).run();if(status==='frozen')await env.DB.prepare('DELETE FROM sessions WHERE player_id=? AND role=\'player\'').bind(playerId).run();return json({ok:true,playerId,status},200,headers)}
    if(path==='/admin/player/logout'&&req.method==='POST'){await requireAdmin(req,env);const b=await body(req),playerId=String(b.playerId||'').trim();if(!playerId)return json({ok:false,error:'INVALID_PLAYER_ID'},400,headers);await env.DB.prepare('DELETE FROM sessions WHERE player_id=? AND role=\'player\'').bind(playerId).run();return json({ok:true,playerId},200,headers)}
    if(path==='/admin/stats'&&req.method==='GET'){await requireAdmin(req,env);const players=await env.DB.prepare('SELECT COUNT(*) AS count,COALESCE(SUM(balance),0) AS total_balance FROM players').first();let ledger={count:0,positive:0,negative:0};try{ledger=await env.DB.prepare("SELECT COUNT(*) AS count,COALESCE(SUM(CASE WHEN delta>0 THEN delta ELSE 0 END),0) AS positive,COALESCE(SUM(CASE WHEN delta<0 THEN -delta ELSE 0 END),0) AS negative FROM balance_ledger").first()||ledger}catch(_){}const today=Date.now()-86400000;let daily={positive:0,negative:0};try{daily=await env.DB.prepare("SELECT COALESCE(SUM(CASE WHEN amount>0 THEN amount ELSE 0 END),0) AS positive,COALESCE(SUM(CASE WHEN amount<0 THEN -amount ELSE 0 END),0) AS negative FROM admin_logs WHERE created_at>=?").bind(today).first()||daily}catch(_){}const setting=await env.DB.prepare("SELECT value FROM admin_settings WHERE key='maintenance'").first().catch(()=>null);return json({ok:true,players:Number(players?.count||0),totalBalance:Number(players?.total_balance||0),ledgerCount:Number(ledger.count||0),ledgerPositive:Number(ledger.positive||0),ledgerNegative:Number(ledger.negative||0),todayGrant:Number(daily.positive||0),todayRevoke:Number(daily.negative||0),maintenance:setting?.value==='1'},200,headers)}
    if((path==='/admin/maintenance'||path==='/admin/emergency-stop')&&req.method==='POST'){await requireAdmin(req,env);const b=await body(req),enabled=!!b.enabled;await env.DB.prepare("INSERT INTO admin_settings(key,value,updated_at) VALUES('maintenance',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").bind(enabled?'1':'0',Date.now()).run();return json({ok:true,maintenance:enabled},200,headers)}
    if(path==='/admin/games'&&req.method==='GET'){await requireAdmin(req,env);const rows=await env.DB.prepare(`SELECT game_type,enabled,maintenance,updated_at FROM game_settings ORDER BY game_type`).all();return json({ok:true,games:rows.results||[]},200,headers)}
    if(path==='/admin/games'&&req.method==='POST'){await requireAdmin(req,env);const b=await body(req),gameType=String(b.gameType||'').toLowerCase();if(!['slot','blackjack','poker','roulette','crash','highlow','chohan','cointoss','highdice','mahjong'].includes(gameType))return json({ok:false,error:'INVALID_GAME_TYPE'},400,headers);const enabled=b.enabled===undefined?1:(b.enabled?1:0),maintenance=b.maintenance?1:0;await env.DB.prepare(`INSERT INTO game_settings(game_type,enabled,maintenance,updated_at) VALUES(?,?,?,?) ON CONFLICT(game_type) DO UPDATE SET enabled=excluded.enabled,maintenance=excluded.maintenance,updated_at=excluded.updated_at`).bind(gameType,enabled,maintenance,Date.now()).run();return json({ok:true,gameType,enabled,maintenance},200,headers)}

    if(path==='/admin/logs'&&req.method==='GET'){await requireAdmin(req,env);const rows=await env.DB.prepare('SELECT id,target_player_id,amount,note,created_at FROM admin_logs ORDER BY id DESC LIMIT 100').all();return json({ok:true,logs:rows.results||[]},200,headers)}
    return json({ok:false,error:'NOT_FOUND'},404,headers);
  }catch(e){const status=Number(e?.status||500);return json({ok:false,error:status===500?'SERVER_ERROR':String(e?.message||e)},status,headers)}
 }};
